application: connexuselvis
version: 1
runtime: python27
api_version: 1
threadsafe: yes




handlers:
- url: /trend
  script: TrendingStreams.app
#  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: Management.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
