application: connexuselvis
version: 1
runtime: python27
api_version: 1
threadsafe: yes




handlers:
- url: /trend
  script: TrendingStreams.app
#  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img


- url: /fonts
  static_dir: fonts

- url: /.*
  script: Management.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
