application: connexus-1104
version: 1
runtime: python27
api_version: 1
threadsafe: true




handlers:
- url: /android_viewall
  script: Android_ViewStreams.app

- url: /android_viewsingle
  script: Android_ViewAStream.app

- url: /android_search
  script: Android_Search.app

- url: /android_upload
  script: Android_ImageUpload.app

- url: /android_getUploadURL
  script: GetUploadURL.app

- url: /Android_ImageUpload
  script: Android_ImageUpload.app

- url: /trend
  script: TrendingStreams.app

- url: /search
  script: SearchStreams.app
#  login: admin

- url: /stylesheets
  static_dir: stylesheets


- url: /images
  static_dir: images

- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /img
  static_dir: img


- url: /fonts
  static_dir: fonts


- url: /data
  static_dir: data



- url: /.*
  script: Management.app
  login: required

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
